jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Make gradlew executable
      run: chmod +x ./gradlew
    - continue-on-error: true
      name: Build
      run: ./gradlew --parallel app:assembleRelease
    strategy:
      matrix:
        java:
        - 11
        - 11.0.3
        os:
        - ubuntu-18.04
        - macOS-latest
        - windows-2016
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
